### ISSUE TITLE
Spotify `1.1.80` React Hooks - "Cannot find symbol for Custom app React"

### ISSUE THREAD

**Issue by Daksh777** [spicetify/spicetify-cli#1514]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.1.80.699.gc3dac750
- Spicetify version: spicetify v2.9.1
```

### 📝 Description

Running `spicetify apply` throws the `Cannot find symbol for Custom app React symbols` error but the theme does get applied.

The following hooks are the ones that need to be updated:
- [x] Custom App React symbols (#1517)
- [x] Spicetify.React (#1517)
- [x] Spicetify.Platform (#1517)
- [x] Spicetify.ReactComponent.RightClickMenu (#1517)
- [x] Spicetify.ReactComponent.ContextMenu (#1517)
- [x] Spicetify.Menu(https://github.com/spicetify/spicetify-cli/pull/1548)
- [x] Spicetify.ReactComponent.Menu(https://github.com/spicetify/spicetify-cli/pull/1548)
- [x] Spicetify.ReactComponent.MenuItem(https://github.com/spicetify/spicetify-cli/pull/1548)
- [ ] Spicetify.ReactComponent.AlbumMenu
- [ ] Spicetify.ReactComponent.PodcastShowMenu
- [ ] Spicetify.ReactComponent.ArtistMenu
- [ ] Spicetify.ReactComponent.PlaylistMenu
- [ ] Home config

**Comment by afonsojramos** [comment]
It seems like a new Spotify version... Here we go updating the regex 😅

**Comment by Basic6969** [comment]
> It seems like a new Spotify version... Here we go updating the regex 😅

when it will be resolved then?

**Comment by afonsojramos** [comment]
@Basic6969 when someone finds the time to do it :)

**Comment by CharlieS1103** [comment]
@afonsojramos updates regex a lil but couldn't figure out rest of issue. I thunk meow is working on it

**Comment by TheMayhem6328** [comment]
Hook refers to a path not in my system...
```
error Cannot find symbol for Custom app React symbols
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp.func1(0xc0006be000, 0x205807, 0x205807, 0xc0006be000)
        C:/Users/Afonso/GitHub/spicetify-cli/src/apply/apply.go:215 +0xda6
github.com/khanhas/spicetify-cli/src/utils.ModifyFile(0xc0000122c0, 0x3d, 0xc000211910)
        C:/Users/Afonso/GitHub/spicetify-cli/src/utils/utils.go:191 +0xdb
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp(0xc0000122c0, 0x3d, 0xc00045a680, 0x7, 0x8, 0xc000042280, 0x3, 0x4, 0x10101, 0xc00000ab11, ...)
        C:/Users/Afonso/GitHub/spicetify-cli/src/apply/apply.go:188 +0xc5
github.com/khanhas/spicetify-cli/src/apply.AdditionalOptions(0xc000010b10, 0x30, 0xc00045a680, 0x7, 0x8, 0xc000042280, 0x3, 0x4, 0x10101, 0xc00000ab11, ...)
        C:/Users/Afonso/GitHub/spicetify-cli/src/apply/apply.go:37 +0x57d
github.com/khanhas/spicetify-cli/src/cmd.Apply(0x928d14, 0x5)
        C:/Users/Afonso/GitHub/spicetify-cli/src/cmd/apply.go:72 +0x68c
main.main()
        C:/Users/Afonso/GitHub/spicetify-cli/spicetify.go:194 +0x4f9
```

**Comment by afonsojramos** [comment]
@TheMayhem6328 Yeah, this is because of how Golang builds its binaries, the debug info indicates the lines of where the package was built, aka, my machine 😅 We could remove this, but it would remove ALL debug info, so not exactly ideal... With the new automated release introduced in #1513 the paths should be a bit more generic!

**Comment by DanBeast1337** [comment]
For me, it's a lot more critical. It does not apply **anything** from Spicetify. Not even the theme. 

Considering just downgrading to .79 at the moment, to make it work again. Any idea?

**Comment by afonsojramos** [comment]
That is expected, just hold on for a bit on `spicetify restore`

**Comment by githubmodssuck** [comment]
Did this error get fixed yet?

**Comment by xerta555** [comment]
> Did this error get fixed yet?

No, wait for the fix if you want to use custom app(s).

**Comment by realparthkhandelwal** [comment]
yeah me too getting the prob

**Comment by J4-C** [comment]
same issue with backing up too

**Comment by JamesGordonII** [comment]
So can we expect this to be fixed in a few days or how long will we not have custom apps?

**Comment by JamesGordonII** [comment]
> 

kk

**Comment by D3SOX** [comment]
https://github.com/spicetify/spicetify-cli/pull/1517 works for me

<details>
<summary>If anyone needs a `PKGBUILD` for it</summary>

```bash
# Maintainer: Francesco Minnocci <ascoli dot mimnnocci at gmail dot com>

_gitname=spicetify-cli
pkgname="${_gitname}-git"
pkgver=2.8.0.r97.g93cf89d
pkgrel=1
pkgdesc='Command-line tool to customize Spotify client - Git master branch'
arch=('x86_64' 'i686')
url="https://github.com/itsmeowForks/${_gitname}"
license=('GPL')
makedepends=('git' 'go')
source=("git+${url}.git")
sha256sums=('SKIP')
provides=("${_gitname}")
conflicts=("${_gitname}")

pkgver() {
	cd "$srcdir/${_gitname}"

  git describe --long --tags | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'
}

prepare() {
	cd "$srcdir/${_gitname}"

  git checkout 80-fixes
}

build() {
	cd "$srcdir/${_gitname}"

  export GOPATH="$srcdir"
  go build -o spicetify
}

check() {
	cd "$srcdir/${_gitname}"

  ./spicetify -v
}

package() {
	cd "$srcdir/${_gitname}"

  install -Dm755 ./spicetify "$pkgdir"/usr/share/${_gitname}/spicetify
  cp -r ./Themes ./css-map.json ./Extensions ./CustomApps ./jsHelper ./globals.d.ts -t "$pkgdir"/usr/share/${_gitname}

  rm -f ./shortcut
  echo "#!/bin/sh
/usr/share/${_gitname}/spicetify \"\$@\"" >> ./shortcut
  install -Dm755 ./shortcut "$pkgdir"/usr/bin/spicetify

  # Clean up deps
  go clean -modcache
}
# vim:set ts=2 sw=2 et:
```

</details>

**Comment by JamesGordonII** [comment]
I keep seeing new releases pop up then 10 minutes later they are gone? are those patches being released then taken down due to a new bug they make?

**Comment by afonsojramos** [comment]
Sorry for the spam @JamesGordonII. Due to the new release process there was some stuff that wasn't 100% tested, but it is fully working now!

**Comment by CharlieS1103** [comment]
Patched a few more hooks, Menu functionality is working normally now. (Should we close this issue @afonsojramos )

**Comment by afonsojramos** [comment]
@CharlieS1103 just close it with the ticket!

**Comment by CharlieS1103** [comment]
> @CharlieS1103 just close it with the ticket!

No clue how to do that

**Comment by afonsojramos** [comment]
Are the other hooks fixed?

**Comment by afonsojramos** [comment]
I believe that with @CharlieS1103's latest regex update every hook should be working so I'll close this.

**Comment by ConaII** [comment]
Happening again
```
error cannot find symbol for Custom app React Element
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/spicetify/spicetify-cli/src/apply.insertCustomApp.func1({0xc000f64000, 0x18aa98})
        /home/runner/work/spicetify-cli/spicetify-cli/src/apply/apply.go:220 +0x987
github.com/spicetify/spicetify-cli/src/utils.ModifyFile({0xc00000fcc0, 0x38}, 0xc0003ff8d8)
        /home/runner/work/spicetify-cli/spicetify-cli/src/utils/utils.go:191 +0x7b
github.com/spicetify/spicetify-cli/src/apply.insertCustomApp({0xc00000fcc0, 0x3b}, {{0x142cff8, 0x0, 0x0}, {0xc000d100e0, 0x1, 0x2}, 0x1, 0x1, ...})
        /home/runner/work/spicetify-cli/spicetify-cli/src/apply/apply.go:188 +0x90
github.com/spicetify/spicetify-cli/src/apply.AdditionalOptions({0xc00000cab0, 0x2b}, {{0x142cff8, 0x0, 0x0}, {0xc000d100e0, 0x1, 0x2}, 0x1, 0x1, ...})
        /home/runner/work/spicetify-cli/spicetify-cli/src/apply/apply.go:37 +0x4c3
github.com/spicetify/spicetify-cli/src/cmd.Apply({0x11fb7f8, 0x5})
        /home/runner/work/spicetify-cli/spicetify-cli/src/cmd/apply.go:72 +0x9ae
main.main()
        /home/runner/work/spicetify-cli/spicetify-cli/spicetify.go:225 +0x77b
```
